//! FSR golden tests: open a snapshot, drive its Full State Reconstruction plan through
//! the [`DataFusionExecutor`], pretty-print the reconstructed actions, and compare
//! against a frozen expected string.
//!
//! Per fixture the recipe is exactly four steps:
//!   1. `open_snapshot_for_fixture(fixture)` -> `(engine, snapshot)`
//!   2. `snapshot.full_state_builder().build()` -> `FullState`
//!   3. `executor.full_state(&fsr).await?.collect().await?` -> `Vec<RecordBatch>`
//!   4. `datafusion_common::assert_batches_sorted_eq!` against the expected lines.
//!
//! Each `EXPECTED_*` const was captured from this same path and then cross-checked against an
//! independent source of truth before being frozen here: the FSR result's `add.path` set is
//! verified row-for-row against the kernel default-engine `scan_metadata` add-path set (the
//! classic kernel reference replay through `DefaultEngineBuilder`). After that the golden is
//! frozen: any future code change that perturbs the output forces an explicit re-validate-and-
//! update cycle.

mod common;

use std::path::PathBuf;
use std::sync::Arc;

use datafusion_common::assert_batches_sorted_eq;
use delta_kernel::engine::default::DefaultEngineBuilder;
use delta_kernel::object_store::local::LocalFileSystem;
use delta_kernel::{Engine as KernelEngine, Snapshot};
use delta_kernel_datafusion_engine::DataFusionExecutor;
use rstest::rstest;
use tempfile::TempDir;
use url::Url;

struct FixtureTable {
    _tmp: Option<TempDir>,
    url: Url,
}

fn fixture_table(name: &str) -> FixtureTable {
    let data_root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../kernel/tests/data");
    let direct = data_root.join(name);
    if direct.is_dir() {
        return FixtureTable {
            _tmp: None,
            url: Url::from_directory_path(direct.canonicalize().expect("fixture path"))
                .expect("table url"),
        };
    }

    let tmp = test_utils::load_test_data("../kernel/tests/data", name)
        .unwrap_or_else(|e| panic!("load archived fixture {name}: {e}"));
    let extracted = tmp.path().join(name);
    assert!(
        extracted.is_dir(),
        "archived fixture extraction missing directory: {}",
        extracted.display()
    );
    FixtureTable {
        _tmp: Some(tmp),
        url: Url::from_directory_path(extracted.canonicalize().expect("extracted fixture path"))
            .expect("table url"),
    }
}

fn default_engine() -> Arc<dyn KernelEngine> {
    Arc::new(DefaultEngineBuilder::new(Arc::new(LocalFileSystem::new())).build())
}

fn open_snapshot_for_fixture(table: &str) -> (Arc<dyn KernelEngine>, Arc<Snapshot>) {
    let engine = default_engine();
    let snapshot = Snapshot::builder_for(fixture_table(table).url)
        .build(engine.as_ref())
        .expect("snapshot");
    (engine, snapshot)
}

// validated against kernel default-engine `scan_metadata` add-path set.
const EXPECTED_APP_TXN_NO_CHECKPOINT: &str = r#"
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+--------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+---------------------------------------------+
| add                                                                                                                                                                                                                                                                                                                                                                                                                       | remove | protocol                                                                       | metaData                                                                                                                                                                                                                                                                                                                                                                                                                           | domainMetadata | txn                                         |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+--------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+---------------------------------------------+
| {path: modified=2021-02-01/part-00001-80996595-a345-43b7-b213-e247d6f091f7-c000.snappy.parquet, partitionValues: {modified: 2021-02-01}, size: 810, modificationTime: 1713400714557, dataChange: true, stats: {"numRecords":8,"minValues":{"value":4,"id":"A"},"maxValues":{"id":"B","value":11},"nullCount":{"id":0,"value":0}}, tags: , deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                    |                |                                             |
| {path: modified=2021-02-02/part-00001-9a16b9f6-c12a-4609-a9c4-828eacb9526a-c000.snappy.parquet, partitionValues: {modified: 2021-02-02}, size: 789, modificationTime: 1713400714564, dataChange: true, stats: {"numRecords":3,"minValues":{"value":1,"id":"A"},"maxValues":{"id":"B","value":3},"nullCount":{"id":0,"value":0}}, tags: , deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: }  |        |                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                    |                |                                             |
| {path: modified=2021-02-02/part-00001-bfac5c74-426e-410f-ab74-21a64e518e9c-c000.snappy.parquet, partitionValues: {modified: 2021-02-02}, size: 789, modificationTime: 1713400714557, dataChange: true, stats: {"numRecords":3,"minValues":{"id":"A","value":1},"maxValues":{"value":3,"id":"B"},"nullCount":{"value":0,"id":0}}, tags: , deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: }  |        |                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                    |                |                                             |
| {path: modified=2021-02-01/part-00001-8ebcaf8b-0f48-4213-98c9-5c2156d20a7e-c000.snappy.parquet, partitionValues: {modified: 2021-02-01}, size: 810, modificationTime: 1713400714564, dataChange: true, stats: {"numRecords":8,"minValues":{"value":4,"id":"A"},"maxValues":{"value":11,"id":"B"},"nullCount":{"id":0,"value":0}}, tags: , deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                    |                |                                             |
|                                                                                                                                                                                                                                                                                                                                                                                                                           |        |                                                                                | {id: dc67687f-4462-4bc9-9070-b53a58e4780e, name: , description: , format: {provider: parquet, options: {}}, schemaString: {"type":"struct","fields":[{"name":"id","type":"string","nullable":true,"metadata":{}},{"name":"value","type":"integer","nullable":true,"metadata":{}},{"name":"modified","type":"string","nullable":true,"metadata":{}}]}, partitionColumns: [modified], createdTime: 1713400714555, configuration: {}} |                |                                             |
|                                                                                                                                                                                                                                                                                                                                                                                                                           |        | {minReaderVersion: 1, minWriterVersion: 2, readerFeatures: , writerFeatures: } |                                                                                                                                                                                                                                                                                                                                                                                                                                    |                |                                             |
|                                                                                                                                                                                                                                                                                                                                                                                                                           |        |                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                    |                | {appId: my-app2, version: 2, lastUpdated: } |
|                                                                                                                                                                                                                                                                                                                                                                                                                           |        |                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                    |                | {appId: my-app, version: 3, lastUpdated: }  |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+--------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+---------------------------------------------+
"#;

// validated against kernel default-engine `scan_metadata` add-path set.
const EXPECTED_APP_TXN_CHECKPOINT: &str = r#"
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+--------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+---------------------------------------------+
| add                                                                                                                                                                                                                                                                                                                                                                                                                          | remove | protocol                                                                       | metaData                                                                                                                                                                                                                                                                                                                                                                                                                           | domainMetadata | txn                                         |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+--------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+---------------------------------------------+
|                                                                                                                                                                                                                                                                                                                                                                                                                              |        | {minReaderVersion: 1, minWriterVersion: 2, readerFeatures: , writerFeatures: } |                                                                                                                                                                                                                                                                                                                                                                                                                                    |                |                                             |
| {path: modified=2021-02-02/part-00001-f968feb7-7f54-40c5-8aea-6a3b7a406d9c-c000.snappy.parquet, partitionValues: {modified: 2021-02-02}, size: 789, modificationTime: 1713400874285, dataChange: false, stats: {"numRecords":3,"minValues":{"id":"A","value":1},"maxValues":{"id":"B","value":3},"nullCount":{"id":0,"value":0}}, tags: {}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: }  |        |                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                    |                |                                             |
| {path: modified=2021-02-01/part-00001-7e32952f-35ad-423c-8926-dbd3d264b1ee-c000.snappy.parquet, partitionValues: {modified: 2021-02-01}, size: 810, modificationTime: 1713400874277, dataChange: false, stats: {"numRecords":8,"minValues":{"id":"A","value":4},"maxValues":{"value":11,"id":"B"},"nullCount":{"id":0,"value":0}}, tags: {}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                    |                |                                             |
| {path: modified=2021-02-02/part-00001-5113d412-8632-458b-a49a-f34db1069081-c000.snappy.parquet, partitionValues: {modified: 2021-02-02}, size: 789, modificationTime: 1713400874277, dataChange: false, stats: {"numRecords":3,"minValues":{"value":1,"id":"A"},"maxValues":{"value":3,"id":"B"},"nullCount":{"id":0,"value":0}}, tags: {}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: }  |        |                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                    |                |                                             |
|                                                                                                                                                                                                                                                                                                                                                                                                                              |        |                                                                                | {id: e7802058-f49c-4f0b-937f-82a3e42781a3, name: , description: , format: {provider: parquet, options: {}}, schemaString: {"type":"struct","fields":[{"name":"id","type":"string","nullable":true,"metadata":{}},{"name":"value","type":"integer","nullable":true,"metadata":{}},{"name":"modified","type":"string","nullable":true,"metadata":{}}]}, partitionColumns: [modified], createdTime: 1713400874275, configuration: {}} |                |                                             |
| {path: modified=2021-02-01/part-00001-3b6e7f26-8140-4067-8504-47540a363758-c000.snappy.parquet, partitionValues: {modified: 2021-02-01}, size: 810, modificationTime: 1713400874285, dataChange: false, stats: {"numRecords":8,"minValues":{"value":4,"id":"A"},"maxValues":{"id":"B","value":11},"nullCount":{"id":0,"value":0}}, tags: {}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                    |                |                                             |
|                                                                                                                                                                                                                                                                                                                                                                                                                              |        |                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                    |                | {appId: my-app2, version: 2, lastUpdated: } |
|                                                                                                                                                                                                                                                                                                                                                                                                                              |        |                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                    |                | {appId: my-app, version: 3, lastUpdated: }  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+--------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+---------------------------------------------+
"#;

// validated against kernel default-engine `scan_metadata` add-path set.
const EXPECTED_DV_SMALL: &str = r#"
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
| add                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | remove | protocol                                                                                                         | metaData                                                                                                                                                                                                                                                                                                                        | domainMetadata | txn |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |        | {minReaderVersion: 3, minWriterVersion: 7, readerFeatures: [deletionVectors], writerFeatures: [deletionVectors]} |                                                                                                                                                                                                                                                                                                                                 |                |     |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |        |                                                                                                                  | {id: testId, name: , description: , format: {provider: parquet, options: {}}, schemaString: {"type":"struct","fields":[{"name":"value","type":"integer","nullable":true,"metadata":{}}]}, partitionColumns: [], createdTime: 1677811175819, configuration: {delta.enableDeletionVectors: true, delta.columnMapping.mode: none}} |                |     |
| {path: part-00000-fae5310a-a37d-4e51-827b-c3d5516560ca-c000.snappy.parquet, partitionValues: {}, size: 635, modificationTime: 1677811178336, dataChange: true, stats: {"numRecords":10,"minValues":{"value":0},"maxValues":{"value":9},"nullCount":{"value":0},"tightBounds":false}, tags: {INSERTION_TIME: 1677811178336000, MIN_INSERTION_TIME: 1677811178336000, MAX_INSERTION_TIME: 1677811178336000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: {storageType: u, pathOrInlineDv: vBn[lx{q8@P<9BNH/isA, offset: 1, sizeInBytes: 36, cardinality: 2}, baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                  |                                                                                                                                                                                                                                                                                                                                 |                |     |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
"#;

// validated against kernel default-engine `scan_metadata` add-path set.
const EXPECTED_NO_DV_SMALL: &str = r#"
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+--------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
| add                                                                                                                                                                                                                                                                                                                                                      | remove | protocol                                                                       | metaData                                                                                                                                                                                                                                                                                  | domainMetadata | txn |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+--------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
|                                                                                                                                                                                                                                                                                                                                                          |        |                                                                                | {id: 6524c99f-9a76-4ea1-8ad4-e428a7e065d7, name: , description: , format: {provider: parquet, options: {}}, schemaString: {"type":"struct","fields":[{"name":"value","type":"long","nullable":true,"metadata":{}}]}, partitionColumns: [], createdTime: 1678020184802, configuration: {}} |                |     |
|                                                                                                                                                                                                                                                                                                                                                          |        | {minReaderVersion: 1, minWriterVersion: 2, readerFeatures: , writerFeatures: } |                                                                                                                                                                                                                                                                                           |                |     |
| {path: part-00000-517f5d32-9c95-48e8-82b4-0229cc194867-c000.snappy.parquet, partitionValues: {}, size: 548, modificationTime: 1678020185157, dataChange: true, stats: {"numRecords":10,"minValues":{"value":0},"maxValues":{"value":9},"nullCount":{"value":0}}, tags: , deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                |                                                                                                                                                                                                                                                                                           |                |     |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+--------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
"#;

// validated against kernel default-engine `scan_metadata` add-path set.
const EXPECTED_SHORT_DV: &str = r#"
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
| add                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | remove | protocol                                                                                                         | metaData                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | domainMetadata | txn |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |        | {minReaderVersion: 3, minWriterVersion: 7, readerFeatures: [deletionVectors], writerFeatures: [deletionVectors]} |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |                |     |
| {path: part-00000-8029f411-746c-41c1-a0c1-c5eb867c5d05-c000.snappy.parquet, partitionValues: {}, size: 1423, modificationTime: 1685559514000, dataChange: true, stats: {"numRecords":5,"minValues":{"id":0,"value":"0","timestamp":"2023-05-31T18:58:33.633Z","rand":0.1001744351184638},"maxValues":{"id":4,"value":"4","timestamp":"2023-05-31T18:58:33.633Z","rand":0.9281049271981882},"nullCount":{"id":0,"value":0,"timestamp":0,"rand":0},"tightBounds":false}, tags: , deletionVector: {storageType: u, pathOrInlineDv: U5OWRz5k%CFT.Td}yCPW, offset: 1, sizeInBytes: 38, cardinality: 3}, baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |                |     |
| {path: part-00001-24db34ab-bdfe-4814-aba8-c1f34d6d8923-c000.snappy.parquet, partitionValues: {}, size: 1428, modificationTime: 1685559514000, dataChange: true, stats: {"numRecords":5,"minValues":{"id":5,"value":"5","timestamp":"2023-05-31T18:58:33.633Z","rand":0.15263801464228832},"maxValues":{"id":9,"value":"9","timestamp":"2023-05-31T18:58:33.633Z","rand":0.5175919190815845},"nullCount":{"id":0,"value":0,"timestamp":0,"rand":0},"tightBounds":true}, tags: , deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: }                                                                                                   |        |                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |                |     |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |        |                                                                                                                  | {id: 7f10249f-e3ff-4fe4-967a-05637934a7e9, name: , description: Deletion vectors enabled table. The latest version has DVs turned on and DVs present in the table., format: {provider: parquet, options: {}}, schemaString: {"type":"struct","fields":[{"name":"id","type":"long","nullable":true,"metadata":{}},{"name":"value","type":"string","nullable":true,"metadata":{}},{"name":"timestamp","type":"timestamp","nullable":true,"metadata":{}},{"name":"rand","type":"double","nullable":true,"metadata":{}}]}, partitionColumns: [], createdTime: 1685559511124, configuration: {delta.enableDeletionVectors: true, delta.checkpointInterval: 10000}} |                |     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
"#;

// validated against kernel default-engine `scan_metadata` add-path set.
const EXPECTED_CHECKPOINT_NO_LAST_CHECKPOINT: &str = r#"
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+--------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
| add                                                                                                                                                                                                                                                                                                                                                                                                                                         | remove | protocol                                                                       | metaData                                                                                                                                                                                                                                                                                                                                                                                                                                       | domainMetadata | txn |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+--------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
| {path: part-00000-70b1dcdf-0236-4f63-a072-124cdbafd8a0-c000.snappy.parquet, partitionValues: {}, size: 1010, modificationTime: 1674611461541, dataChange: true, stats: {"numRecords":5,"minValues":{"letter":"a","int":93,"date":"1975-06-01"},"maxValues":{"letter":"c","int":753,"date":"2013-03-01"},"nullCount":{"letter":1,"int":0,"date":0}}, tags: , deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                |     |
|                                                                                                                                                                                                                                                                                                                                                                                                                                             |        | {minReaderVersion: 1, minWriterVersion: 2, readerFeatures: , writerFeatures: } |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                |     |
|                                                                                                                                                                                                                                                                                                                                                                                                                                             |        |                                                                                | {id: 84b09beb-329c-4b5e-b493-f58c6c78b8fd, name: , description: , format: {provider: parquet, options: {}}, schemaString: {"type":"struct","fields":[{"name":"letter","type":"string","nullable":true,"metadata":{}},{"name":"int","type":"long","nullable":true,"metadata":{}},{"name":"date","type":"date","nullable":true,"metadata":{}}]}, partitionColumns: [], createdTime: 1674611455081, configuration: {delta.checkpointInterval: 2}} |                |     |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+--------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
"#;

// validated against kernel default-engine `scan_metadata` add-path set.
const EXPECTED_V2_CLASSIC_PARQUET: &str = r#"
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
| add                                                                                                                                                                                                                                                                                                                                                                                                                                  | remove | protocol                                                                                                                                 | metaData                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | domainMetadata | txn |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
| {path: test%25file%25prefix-part-00000-bb4858c3-3c9a-4325-ab3f-a0e07e6a94d4-c000.snappy.parquet, partitionValues: {}, size: 760, modificationTime: 1774385173080, dataChange: false, stats: , tags: {INSERTION_TIME: 1774385173080000, MIN_INSERTION_TIME: 1774385173080000, MAX_INSERTION_TIME: 1774385173080000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                |     |
| {path: test%25file%25prefix-part-00000-f91cd7b7-b47f-4f76-b052-971c4a313235-c000.snappy.parquet, partitionValues: {}, size: 761, modificationTime: 1774385174928, dataChange: false, stats: , tags: {INSERTION_TIME: 1774385174928000, MIN_INSERTION_TIME: 1774385174928000, MAX_INSERTION_TIME: 1774385174928000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                |     |
| {path: test%25file%25prefix-part-00000-1f06e739-2467-49d8-bec1-dffa9c6ca027-c000.snappy.parquet, partitionValues: {}, size: 761, modificationTime: 1774385174004, dataChange: false, stats: , tags: {INSERTION_TIME: 1774385174004000, MIN_INSERTION_TIME: 1774385174004000, MAX_INSERTION_TIME: 1774385174004000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                |     |
|                                                                                                                                                                                                                                                                                                                                                                                                                                      |        | {minReaderVersion: 3, minWriterVersion: 7, readerFeatures: [deletionVectors], writerFeatures: [deletionVectors, appendOnly, invariants]} |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                |     |
| {path: test%25file%25prefix-part-00000-981d116a-6a3c-4c09-b604-3695d0db5dc8-c000.snappy.parquet, partitionValues: {}, size: 761, modificationTime: 1774385171192, dataChange: false, stats: , tags: {INSERTION_TIME: 1774385171192000, MIN_INSERTION_TIME: 1774385171192000, MAX_INSERTION_TIME: 1774385171192000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                |     |
|                                                                                                                                                                                                                                                                                                                                                                                                                                      |        |                                                                                                                                          | {id: 23b172f9-95c3-43d0-8c0c-423bb644526a, name: , description: , format: {provider: parquet, options: {}}, schemaString: {"type":"struct","fields":[{"name":"id","type":"long","nullable":true,"metadata":{}},{"name":"value","type":"string","nullable":true,"metadata":{}}]}, partitionColumns: [], createdTime: 1774385170349, configuration: {delta.enableDeletionVectors: true, delta.checkpoint.writeStatsAsStruct: true, delta.checkpointPolicy: classic, delta.checkpoint.writeStatsAsJson: false, delta.checkpointInterval: 10}} |                |     |
| {path: test%25file%25prefix-part-00000-e2cba303-0dc3-4091-87cb-ce11d0447bda-c000.snappy.parquet, partitionValues: {}, size: 761, modificationTime: 1774385172140, dataChange: false, stats: , tags: {INSERTION_TIME: 1774385172140000, MIN_INSERTION_TIME: 1774385172140000, MAX_INSERTION_TIME: 1774385172140000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                |     |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
"#;

// validated against kernel default-engine `scan_metadata` add-path set.
const EXPECTED_V2_JSON_SIDECARS: &str = r#"
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
| add                                                                                                                                                                                                                                                                                                                                                                                                                                  | remove | protocol                                                                                                                                                             | metaData                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | domainMetadata | txn |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
| {path: test%25file%25prefix-part-00000-68f487f2-d7f8-48d8-8b34-4a567dc046f4-c000.snappy.parquet, partitionValues: {}, size: 760, modificationTime: 1774385167032, dataChange: false, stats: , tags: {INSERTION_TIME: 1774385167032000, MIN_INSERTION_TIME: 1774385167032000, MAX_INSERTION_TIME: 1774385167032000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                |     |
| {path: test%25file%25prefix-part-00000-c89fe644-eade-4db6-b00f-6c5e1f8343ea-c000.snappy.parquet, partitionValues: {}, size: 761, modificationTime: 1774385168156, dataChange: false, stats: , tags: {INSERTION_TIME: 1774385168156000, MIN_INSERTION_TIME: 1774385168156000, MAX_INSERTION_TIME: 1774385168156000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                |     |
|                                                                                                                                                                                                                                                                                                                                                                                                                                      |        | {minReaderVersion: 3, minWriterVersion: 7, readerFeatures: [deletionVectors, v2Checkpoint], writerFeatures: [deletionVectors, v2Checkpoint, appendOnly, invariants]} |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                |     |
| {path: test%25file%25prefix-part-00000-b93d3d1f-a7ec-42f2-ade5-27837538abcd-c000.snappy.parquet, partitionValues: {}, size: 761, modificationTime: 1774385165060, dataChange: false, stats: , tags: {INSERTION_TIME: 1774385165060000, MIN_INSERTION_TIME: 1774385165060000, MAX_INSERTION_TIME: 1774385165060000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                |     |
|                                                                                                                                                                                                                                                                                                                                                                                                                                      |        |                                                                                                                                                                      | {id: aab52b7c-387a-4e1b-b804-4140a460bfd6, name: , description: , format: {provider: parquet, options: {}}, schemaString: {"type":"struct","fields":[{"name":"id","type":"long","nullable":true,"metadata":{}},{"name":"value","type":"string","nullable":true,"metadata":{}}]}, partitionColumns: [], createdTime: 1774385164156, configuration: {delta.enableDeletionVectors: true, delta.checkpoint.writeStatsAsStruct: true, delta.checkpointPolicy: v2, delta.checkpoint.writeStatsAsJson: false, delta.checkpointInterval: 10}} |                |     |
| {path: test%25file%25prefix-part-00000-e4fcdaa7-dff0-4c20-b263-fc29f1cba12c-c000.snappy.parquet, partitionValues: {}, size: 761, modificationTime: 1774385169176, dataChange: false, stats: , tags: {INSERTION_TIME: 1774385169176000, MIN_INSERTION_TIME: 1774385169176000, MAX_INSERTION_TIME: 1774385169176000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                |     |
| {path: test%25file%25prefix-part-00000-4c7c7cd8-3a62-4e66-b3b9-e89f44612e30-c000.snappy.parquet, partitionValues: {}, size: 761, modificationTime: 1774385166068, dataChange: false, stats: , tags: {INSERTION_TIME: 1774385166068000, MIN_INSERTION_TIME: 1774385166068000, MAX_INSERTION_TIME: 1774385166068000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                |     |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
"#;

// validated against kernel default-engine `scan_metadata` add-path set.
const EXPECTED_V2_PARQUET_SIDECARS: &str = r#"
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
| add                                                                                                                                                                                                                                                                                                                                                                                                                                  | remove | protocol                                                                                                                                                             | metaData                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | domainMetadata | txn |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
|                                                                                                                                                                                                                                                                                                                                                                                                                                      |        | {minReaderVersion: 3, minWriterVersion: 7, readerFeatures: [deletionVectors, v2Checkpoint], writerFeatures: [deletionVectors, v2Checkpoint, appendOnly, invariants]} |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                |     |
|                                                                                                                                                                                                                                                                                                                                                                                                                                      |        |                                                                                                                                                                      | {id: 69f7cd6b-63b4-4e31-85b1-450ac0a9f70e, name: , description: , format: {provider: parquet, options: {}}, schemaString: {"type":"struct","fields":[{"name":"id","type":"long","nullable":true,"metadata":{}},{"name":"value","type":"string","nullable":true,"metadata":{}}]}, partitionColumns: [], createdTime: 1774385157314, configuration: {delta.enableDeletionVectors: true, delta.checkpoint.writeStatsAsStruct: true, delta.checkpointPolicy: v2, delta.checkpoint.writeStatsAsJson: false, delta.checkpointInterval: 10}} |                |     |
| {path: test%25file%25prefix-part-00000-2ce1aba3-6914-48d4-b2b3-9cc25d61b211-c000.snappy.parquet, partitionValues: {}, size: 761, modificationTime: 1774385159272, dataChange: false, stats: , tags: {INSERTION_TIME: 1774385159272000, MIN_INSERTION_TIME: 1774385159272000, MAX_INSERTION_TIME: 1774385159272000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                |     |
| {path: test%25file%25prefix-part-00000-7268d56a-7420-4691-8062-5b0c3dbdd803-c000.snappy.parquet, partitionValues: {}, size: 760, modificationTime: 1774385160264, dataChange: false, stats: , tags: {INSERTION_TIME: 1774385160264000, MIN_INSERTION_TIME: 1774385160264000, MAX_INSERTION_TIME: 1774385160264000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                |     |
| {path: test%25file%25prefix-part-00000-ba9dae5e-b947-4940-961f-6cf6a3c2fbfe-c000.snappy.parquet, partitionValues: {}, size: 761, modificationTime: 1774385158244, dataChange: false, stats: , tags: {INSERTION_TIME: 1774385158244000, MIN_INSERTION_TIME: 1774385158244000, MAX_INSERTION_TIME: 1774385158244000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                |     |
| {path: test%25file%25prefix-part-00000-ea8ba2ac-45e6-497c-99e5-ad5b5e78920e-c000.snappy.parquet, partitionValues: {}, size: 761, modificationTime: 1774385161268, dataChange: false, stats: , tags: {INSERTION_TIME: 1774385161268000, MIN_INSERTION_TIME: 1774385161268000, MAX_INSERTION_TIME: 1774385161268000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                |     |
| {path: test%25file%25prefix-part-00000-8a3d46e0-9431-4cbd-b97d-6b62a2be1dc8-c000.snappy.parquet, partitionValues: {}, size: 761, modificationTime: 1774385162256, dataChange: false, stats: , tags: {INSERTION_TIME: 1774385162256000, MIN_INSERTION_TIME: 1774385162256000, MAX_INSERTION_TIME: 1774385162256000, OPTIMIZE_TARGET_SIZE: 268435456}, deletionVector: , baseRowId: , defaultRowCommitVersion: , clusteringProvider: } |        |                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                |     |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
"#;

#[rstest]
#[case::no_checkpoint("app-txn-no-checkpoint", EXPECTED_APP_TXN_NO_CHECKPOINT)]
#[case::v1_checkpoint("app-txn-checkpoint", EXPECTED_APP_TXN_CHECKPOINT)]
#[case::dv_small("table-with-dv-small", EXPECTED_DV_SMALL)]
#[case::no_dv_small("table-without-dv-small", EXPECTED_NO_DV_SMALL)]
#[case::short_dv("with-short-dv", EXPECTED_SHORT_DV)]
#[case::checkpoint_no_last_checkpoint(
    "with_checkpoint_no_last_checkpoint",
    EXPECTED_CHECKPOINT_NO_LAST_CHECKPOINT
)]
#[case::v2_classic_parquet("v2-classic-parquet-struct-stats-only", EXPECTED_V2_CLASSIC_PARQUET)]
#[case::v2_json_sidecars("v2-json-sidecars-struct-stats-only", EXPECTED_V2_JSON_SIDECARS)]
#[case::v2_parquet_sidecars("v2-parquet-sidecars-struct-stats-only", EXPECTED_V2_PARQUET_SIDECARS)]
#[tokio::test]
async fn full_state_prints_expected_results(#[case] fixture: &str, #[case] expected: &str) {
    let (engine, snapshot) = open_snapshot_for_fixture(fixture);
    let executor = DataFusionExecutor::try_new_with_engine(engine).expect("executor");
    let fsr = snapshot
        .full_state_builder()
        .build()
        .expect("build full_state plan");
    let batches = executor
        .full_state(&fsr)
        .await
        .expect("full_state DataFrame")
        .collect()
        .await
        .expect("collect full_state DataFrame");
    let expected_lines: Vec<&str> = expected.trim().lines().collect();
    assert_batches_sorted_eq!(expected_lines, &batches);
}

/// Smoke check that `FullStateBuilder::with_stats()` end-to-end produces an `add.stats_parsed`
/// column in the FSR result schema -- the column must exist and be populated for at least one
/// add row in every checkpoint shape we exercise (commit-only, V1 checkpoint, V2 classic /
/// parquet sidecars / JSON sidecars).
#[rstest]
#[case::commit_only("app-txn-no-checkpoint")]
#[case::v1_checkpoint("app-txn-checkpoint")]
#[case::v2_classic_parquet("v2-classic-parquet-struct-stats-only")]
#[case::v2_json_sidecars("v2-json-sidecars-struct-stats-only")]
#[case::v2_parquet_sidecars("v2-parquet-sidecars-struct-stats-only")]
#[tokio::test]
async fn full_state_with_stats_populates_add_stats_parsed(#[case] fixture: &str) {
    use delta_kernel::arrow::array::{Array, StructArray};

    let (engine, snapshot) = open_snapshot_for_fixture(fixture);
    let executor = DataFusionExecutor::try_new_with_engine(engine).expect("executor");
    let fsr = snapshot
        .full_state_builder()
        .with_stats()
        .build()
        .expect("build full_state plan with stats");
    let batches = executor
        .full_state(&fsr)
        .await
        .expect("full_state DataFrame")
        .collect()
        .await
        .expect("collect full_state DataFrame");

    let mut stats_parsed_seen = false;
    for batch in &batches {
        let add_idx = batch.schema().index_of("add").expect("schema has add");
        let add = batch
            .column(add_idx)
            .as_any()
            .downcast_ref::<StructArray>()
            .expect("add is struct");
        let stats_parsed_idx = add
            .fields()
            .iter()
            .position(|f| f.name() == "stats_parsed")
            .expect("add struct has stats_parsed");
        let stats_parsed = add.column(stats_parsed_idx);
        for row in 0..add.len() {
            if !add.is_null(row) && !stats_parsed.is_null(row) {
                stats_parsed_seen = true;
                break;
            }
        }
        if stats_parsed_seen {
            break;
        }
    }
    assert!(
        stats_parsed_seen,
        "expected at least one populated `add.stats_parsed` row in fixture `{fixture}`",
    );
}
